
name: Terraform Deploy

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure Google Credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_TERRAFORM_DEMO }}
        run: |
          echo "${{ secrets.GCP_TERRAFORM_DEMO }}" > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json

      - name: Terraform Init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_TERRAFORM_DEMO }}
        working-directory: ./iac
        run: terraform init

      - name: Terraform Plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_TERRAFORM_DEMO }}
        working-directory: ./iac
        run: terraform plan

      - name: Terraform Apply
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_TERRAFORM_DEMO }}
        working-directory: ./iac
        run: terraform apply -auto-approve


